# Generated by Django 4.2 on 2023-07-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_message_options_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
